### PR TITLE
Docs/virtualization

### PR DESCRIPTION
**Pull request by B-Griffinn**
# New Documentation

Virtualization.md has been added for team mates that may experience a virtualization error when first running Docker Desktop.

Onboarding.md are reminders for new team mates that are useful for setting up their machines.

### CODE REVIEW

**Comment by B-Griffinn** [comment]
New docs for onboarding ready to go :D

**Comment by bramirez96** [comment]
Thanks for the new docs! Just a couple changes requested, and I'd like to reorganize the Onboarding page slightly before we merge it but nice work!

**Review by bramirez96 — CHANGES_REQUESTED** [review]

**Comment by B-Griffinn** [comment]
@bramirez96 updated and ready to discuss onboarding page when you are ready 👍🏼

**Review by bramirez96 — APPROVED** [review]

**Review by VictorDronov — APPROVED** [review]
Looks Good

**Pull request merged**
